name: audit check

on:
    push:
        paths:
            - '**/Cargo.toml'
            - '**/Cargo.lock'

jobs:
    audit:
        timeout-minutes: 10
        name: 'Rust audit check'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: rustsec/audit-check@v1.4.1
              with:
                token: ${{ secrets.GITHUB_TOKEN }}
