name: tests

on:
  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo output
        uses: Swatinem/rust-cache@v2
      - name: Fmt check
        run: cargo fmt --check

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo output
        uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo output
        uses: Swatinem/rust-cache@v2
      - name: Run clippy
        run: cargo clippy --no-deps --all-targets -- -D warnings

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo output
        uses: Swatinem/rust-cache@v2
      - name: Build docs
        run: cargo doc --no-deps --all-features
        env:
          RUSTFLAGS: "-D warnings"
